### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by CRAZYFAKE** [audreyt/node-webworker-threads#116]
@audreyt 
I don't what happend , when I use npm install webworker-threads,
**There are so many errors, as bellow：**

make: *** [Release/obj.target/WebWorkerThreads/src/WebWorkerThreads.o] Error 1
make: Leaving directory `/mnt/www/nrj_app/node_modules/webworker-threads/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node-v4.4.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.14.23
gyp ERR! command "/usr/local/node-v4.4.7-linux-x64/bin/node" "/usr/local/node-v4.4.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/www/nrj_app/node_modules/webworker-threads
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.14.23
npm ERR! argv "/usr/local/node-v4.4.7-linux-x64/bin/node" "/usr/local/node-v4.4.7-linux-x64/bin/npm" "install" "webworker-threads"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webworker-threads@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/www/nrj_app/node_modules/npm-debug.log

system version：Red Hat Enterprise Linux Server release 6.2 X64
node.js version：4.4.7
node-gyp version：3.4.0

**Comment by simonrutter** [comment]
I too am receiving this error upon trying to install the package:

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Simon\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:395:20)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Simon\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1176:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:361:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Simon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\development\AmazonReportGen\node_modules\webworker-threads
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\Simon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "webworker-threads"
npm ERR! node v6.4.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

Any idea of what we can do about this, Audrey? I'd love to give this a try! 
Many thanks in advance!

**Comment by kferrio** [comment]
Same here but with different versions of npm/node. Zipped log attached.
[npm-debug.zip](https://github.com/audreyt/node-webworker-threads/files/491360/npm-debug.zip)

**Comment by addaleax** [comment]
For the Windows people here: It’s hard to tell from your debug outputs, but if you’re unsure whether you have a compiler installed, you may want to try installing https://www.npmjs.com/package/windows-build-tools.

**Comment by kferrio** [comment]
@addaleax - Thanks. I completely forgot I this is a clean box. Gotta love WIndows...

**Comment by kferrio** [comment]
Well, bummer. Looks like a bona fide build error:

```
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\KBF\Document
s\repos\git\verb\node_modules\webworker-threads\build\WebWorkerThreads.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\KBF\Documents\repos\git\verb\node_modules\webworker-threads
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.6.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\KBF\Documents\repos\git\verb\npm-debug.log
```

**Comment by addaleax** [comment]
@kferrio `npm install -g npm@latest`, or generally any way of updating to `npm >= 3.10.4` should solve that for you. :)

**Comment by kferrio** [comment]
@addaleax -- will do. I'm at npm 3.10.3 and I've gotten complacent since the "bad old days" of a few years ago because node-gyp has been so remarkably stable of late!  I'll report back.

**Comment by addaleax** [comment]
@kferrio glad things at least kind of worked out for you! :)

**Comment by brodybits** [comment]
Needs documentation

**Comment by deepakshrma** [comment]
From last 2 days, I am trying to solve. I did all the things mentioned here still getting error, Frustrating now :(
I also tried 
[issues-120](https://github.com/audreyt/node-webworker-threads/issues/120)

Log:
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dvishwakarma\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:2
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dvishwakarma\\AppData\\Roaming\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\
gyp ERR! cwd C:\Users\dvishwakarma\Documents\Projects\ECX-dev\ecxorchestrator\node_modules\webworker-threads
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN grunt-jsdoc@0.6.7 requires a peer of grunt@^0.4.0 but none was installed.
npm WARN grunt-mocha-istanbul@2.4.0 requires a peer of grunt@0.4.x but none was installed.
npm WARN sinon-chai@2.7.0 requires a peer of sinon@>=1.4.0 <2 but none was installed.
npm WARN ecx-orchestrator@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "webworker-threads@0.7.8"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dvishwakarma\Documents\Projects\ECX-dev\ecxorchestrator\npm-debug.log
```

**Comment by brodybits** [comment]
I marked this as **help wanted** for **windows**. I hope to try this on Windows next week but cannot promise for sure.

**Comment by deepakshrma** [comment]
I understand,  sorry :) please help guys :D

**Comment by deepakshrma** [comment]
I really  liked ur approach,  but now we are in production.  It hard to upgrade our development  environment :( everyone  expecting a solution..  Please solve it :)

**Comment by MegaArman** [comment]
https://github.com/nodejs/node-gyp/issues/802

^^^ This might help. I spent a couple of hours trying to figure this stuff out on Windows once and quit as I have the option to use a CentOS server for my project (no problems building node-gyp). I know that might not make you feel any better, but that's my 2 cents!

**Comment by wolf0x** [comment]
always get this failure no matter in what kind of windows env..it is really trouble and look for solution here. :)

gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Git\Test\node_modules\webworker-threads
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "natural"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! webworker-threads@0.7.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webworker-threads@0.7.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webworker-threads package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webworker-threads
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webworker-threads
npm ERR! There is likely additional logging output above.

**Comment by stepanrafael** [comment]
Webworker-threads module are not found after install, the module is added in node_modules and then is automatically removed from the list, also the npm throw a lot of errors.

**Comment by oussemamzoughi** [comment]
any solution ? i had the same error but in linux ..

**Comment by vishnu-meera** [comment]
@stepanrafael please see @addaleax comment.
That will fix the error in windows , the error might be coming due to the absence python 2X.

**Comment by prescottbreeden** [comment]
similar issue on linux: 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.0-7648-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```
I have python v2.7.17 and python3 v3.7.5

**Comment by marcosdipaolo** [comment]
any solution?
